<%
var_ptitle = Null
var_pname = Null
var_ver = Null
var_tz = Null
var_backuptime = Null
var_backuprecent = Null
var_maxperiods = Null
var_emaildomain1 = Null
var_usernames_std = Null
var_usernames_admin = Null
var_firstlogin = Null
var_est_enabled = Null
var_est_enabled_signup = Null
var_est_enabled_pin = Null
var_est_enabled_weekends = Null
var_est_full = Null
var_est_short = Null
var_est_logimg = Null
var_est_stdimg = Null
%>